POST http://localhost:3000/SV1/MastersItems/SubTable/Insert/AsIs/{RowIndex}/{KeyName}
Content-Type: application/json

{
  "Category": "",
  "ItemName": "",
  "Pcs": "",
  "WashType": "",
  "DryWashRate": ""
}