POST http://localhost:3000/SV2/BranOrdersKKD/SubTable/Insert/AsIs/{RowIndex}/{KeyName}
Content-Type: application/json

{
  "ItemInOrder": "",
  "CustomerData": "",
  "OrderData": "",
  "AddOn": "",
  "CheckOutData": ""
}