POST http://localhost:3000/SV2/BranOrdersKKD/Alter/ColumnsWithPk/{pk}
Content-Type: application/json

{
  "ItemInOrder": "",
  "CustomerData": "",
  "OrderData": "",
  "AddOn": "",
  "CheckOutData": ""
}