POST http://localhost:3000/SV3/BranOrdersKKD/Insert/ColumnExist
Content-Type: application/json

{
  "ItemsInOrder": "",
  "CustomerData": "",
  "OrderData": "",
  "AddOnData": "",
  "CheckOutData": ""
}