POST http://localhost:7318/binV4/QrCodes/Create/SendMail
Content-Type: application/json

{"ItemSerial":0,"Category":"","ItemName":"","location":"","Pcs":0,"Rate":0,"DisPer":0,"Total":0,"OrderNumber":0}