import express from 'express';

var router = express.Router();

import { router as RouterForBackupLog } from './BackupLog/routes.js';
import { router as RouterForBranOrdersANFO } from './BranOrdersANFO/routes.js';
import { router as RouterForBranOrdersCSO } from './BranOrdersCSO/routes.js';
import { router as RouterForBranOrdersGD } from './BranOrdersGD/routes.js';
import { router as RouterForBranOrdersGWK } from './BranOrdersGWK/routes.js';
import { router as RouterForBranOrdersKKD } from './BranOrdersKKD/routes.js';
import { router as RouterForBranOrdersKPA } from './BranOrdersKPA/routes.js';
import { router as RouterForBranOrdersLBC } from './BranOrdersLBC/routes.js';
import { router as RouterForBranOrdersMSNvzm } from './BranOrdersMSNvzm/routes.js';
import { router as RouterForBranOrdersMVP } from './BranOrdersMVP/routes.js';
import { router as RouterForBranOrdersNGGOS } from './BranOrdersNGGOS/routes.js';
import { router as RouterForBranOrdersSP } from './BranOrdersSP/routes.js';
import { router as RouterForBranOrdersVG } from './BranOrdersVG/routes.js';
import { router as RouterForBranOrdersVMSN } from './BranOrdersVMSN/routes.js';
import { router as RouterForBranOrdersVRNB } from './BranOrdersVRNB/routes.js';
import { router as RouterForBranOrdersVUDA } from './BranOrdersVUDA/routes.js';
import { router as RouterForBranOrdersYD } from './BranOrdersYD/routes.js';
import { router as RouterForBranToFactBScan } from './BranToFactBScan/routes.js';
import { router as RouterForBranToFactDC } from './BranToFactDC/routes.js';
import { router as RouterForBranToFactFScan } from './BranToFactFScan/routes.js';
import { router as RouterForCompletionDC } from './CompletionDC/routes.js';
import { router as RouterForCompletionScan } from './CompletionScan/routes.js';
import { router as RouterForEntryCancelDc } from './EntryCancelDc/routes.js';
import { router as RouterForEntryCancelScan } from './EntryCancelScan/routes.js';
import { router as RouterForFactoryOut_DC } from './FactoryOut_DC/routes.js';
import { router as RouterForFactoryOut_QrCodeScan } from './FactoryOut_QrCodeScan/routes.js';
import { router as RouterForF_F_Completion_Scan } from './F_F_Completion_Scan/routes.js';
import { router as RouterForF_F_Entry_Return_Scan } from './F_F_Entry_Return_Scan/routes.js';
import { router as RouterForF_F_Pressing_Return_Scan } from './F_F_Pressing_Return_Scan/routes.js';
import { router as RouterForF_F_Washing_Return_Scan } from './F_F_Washing_Return_Scan/routes.js';
import { router as RouterForMastersAddOns } from './MastersAddOns/routes.js';
import { router as RouterForMastersCustomers } from './MastersCustomers/routes.js';
import { router as RouterForMastersItemCategory } from './MastersItemCategory/routes.js';
import { router as RouterForMastersItems } from './MastersItems/routes.js';
import { router as RouterForMastersItemService } from './MastersItemService/routes.js';
import { router as RouterForMastersItemTypes } from './MastersItemTypes/routes.js';
import { router as RouterForPressingCancelDC } from './PressingCancelDC/routes.js';
import { router as RouterForPressingCancelScan } from './PressingCancelScan/routes.js';
import { router as RouterForPressingDC } from './PressingDC/routes.js';
import { router as RouterForPressingScan } from './PressingScan/routes.js';
import { router as RouterForPress_ReWashDC } from './Press_ReWashDC/routes.js';
import { router as RouterForPress_ReWashScan } from './Press_ReWashScan/routes.js';
import { router as RouterForQrCodes } from './QrCodes/routes.js';
import { router as RouterForReWashScan } from './ReWashScan/routes.js';
import { router as RouterForTo_Delivery_Scan } from './To_Delivery_Scan/routes.js';
import { router as RouterForWashingCancelScan } from './WashingCancelScan/routes.js';
import { router as RouterForWashingDC } from './WashingDC/routes.js';
import { router as RouterForWashingScan } from './WashingScan/routes.js';

router.use('/BackupLog', RouterForBackupLog);
router.use('/BranOrdersANFO', RouterForBranOrdersANFO);
router.use('/BranOrdersCSO', RouterForBranOrdersCSO);
router.use('/BranOrdersGD', RouterForBranOrdersGD);
router.use('/BranOrdersGWK', RouterForBranOrdersGWK);
router.use('/BranOrdersKKD', RouterForBranOrdersKKD);
router.use('/BranOrdersKPA', RouterForBranOrdersKPA);
router.use('/BranOrdersLBC', RouterForBranOrdersLBC);
router.use('/BranOrdersMSNvzm', RouterForBranOrdersMSNvzm);
router.use('/BranOrdersMVP', RouterForBranOrdersMVP);
router.use('/BranOrdersNGGOS', RouterForBranOrdersNGGOS);
router.use('/BranOrdersSP', RouterForBranOrdersSP);
router.use('/BranOrdersVG', RouterForBranOrdersVG);
router.use('/BranOrdersVMSN', RouterForBranOrdersVMSN);
router.use('/BranOrdersVRNB', RouterForBranOrdersVRNB);
router.use('/BranOrdersVUDA', RouterForBranOrdersVUDA);
router.use('/BranOrdersYD', RouterForBranOrdersYD);
router.use('/BranToFactBScan', RouterForBranToFactBScan);
router.use('/BranToFactDC', RouterForBranToFactDC);
router.use('/BranToFactFScan', RouterForBranToFactFScan);
router.use('/CompletionDC', RouterForCompletionDC);
router.use('/CompletionScan', RouterForCompletionScan);
router.use('/EntryCancelDc', RouterForEntryCancelDc);
router.use('/EntryCancelScan', RouterForEntryCancelScan);
router.use('/FactoryOut_DC', RouterForFactoryOut_DC);
router.use('/FactoryOut_QrCodeScan', RouterForFactoryOut_QrCodeScan);
router.use('/F_F_Completion_Scan', RouterForF_F_Completion_Scan);
router.use('/F_F_Entry_Return_Scan', RouterForF_F_Entry_Return_Scan);
router.use('/F_F_Pressing_Return_Scan', RouterForF_F_Pressing_Return_Scan);
router.use('/F_F_Washing_Return_Scan', RouterForF_F_Washing_Return_Scan);
router.use('/MastersAddOns', RouterForMastersAddOns);
router.use('/MastersCustomers', RouterForMastersCustomers);
router.use('/MastersItemCategory', RouterForMastersItemCategory);
router.use('/MastersItems', RouterForMastersItems);
router.use('/MastersItemService', RouterForMastersItemService);
router.use('/MastersItemTypes', RouterForMastersItemTypes);
router.use('/PressingCancelDC', RouterForPressingCancelDC);
router.use('/PressingCancelScan', RouterForPressingCancelScan);
router.use('/PressingDC', RouterForPressingDC);
router.use('/PressingScan', RouterForPressingScan);
router.use('/Press_ReWashDC', RouterForPress_ReWashDC);
router.use('/Press_ReWashScan', RouterForPress_ReWashScan);
router.use('/QrCodes', RouterForQrCodes);
router.use('/ReWashScan', RouterForReWashScan);
router.use('/To_Delivery_Scan', RouterForTo_Delivery_Scan);
router.use('/WashingCancelScan', RouterForWashingCancelScan);
router.use('/WashingDC', RouterForWashingDC);
router.use('/WashingScan', RouterForWashingScan);

export { router };